name: CI - Linux - ROS

on:
  push:
    branches:
      - devel
      - master
  pull_request:
    branches:
      - devel
      - master

jobs:
  CI:
    strategy:
      matrix:
        env:
          - {ROS_DISTRO: humble}
          - {ROS_DISTRO: jazzy}
          - {ROS_DISTRO: rolling}
    env:
      CCACHE_DIR: /github/home/.ccache # Enable ccache
      UPSTREAM_WORKSPACE: dependencies.rosinstall
      CMAKE_ARGS: -DBUILD_WITH_OSQP=ON -DBUILD_WITH_PROXQP=ON -DBUILD_WITH_VECTORIZATION_SUPPORT=OFF  # Simde is not available yet
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      # eiquadprog is not yet available in ROS2
      - run: sed -i "/eiquadprog/d" package.xml
      # This step will fetch/store the directory used by ccache before/after the ci run
      - uses: actions/cache@v4
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}
      # Run industrial_ci
      - uses: 'ros-industrial/industrial_ci@e91348ccb95dbd04e2acad70f80bb3975d2dad15'
        env: ${{ matrix.env }}
